services:
  users:
    build: ./users

    depends_on:
      mysqldb:
        condition: service_healthy

    environment:
      - DATABASE_URL=mysql://yovi_user:yovi_pass@mysqldb:3306/users_db

    container_name: users

    image: ghcr.io/arquisoft/yovi_es5b-users:latest

    ports:
      - "3000:3000"

    networks:
      - monitor-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_GAMEY_URL=http://localhost:4000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es5b-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es5b-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=yovi_user
      - MYSQL_PASSWORD=yovi_pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot_pass || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - monitor-net
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  monitor-net:
    driver: bridge


volumes:
  mysql_data:             # Define el volumen para que los datos no se borren
