services:

  mysql-db:
    image: mysql:8.0
    container_name: yovi_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secreta # Contraseña del root
      - MYSQL_DATABASE=yovi_db      # Docker creará esta base de datos automáticamente
    ports:
      - "3307:3306"
    networks:
      - monitor-net
    volumes:
      - mysql_data:/var/lib/mysql

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es5b-users:latest
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=yovi_db
      - DB_USER=root
      - DB_PASSWORD=secreta
      - DB_HOST=mysql-db
    depends_on:
      - mysql-db
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_GAMEY_URL=http://localhost:4000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es5b-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es5b-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

volumes:
  mysql_data:

networks:
  monitor-net:
    driver: bridge
